# Generated by Django 2.2.7 on 2020-01-19 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200119_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 19, 19, 17, 28, 127568)),
        ),
    ]
