# Generated by Django 2.2.7 on 2020-01-20 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200119_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('P', 'Sale'), ('S', 'Hot'), ('D', 'New')], max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 20, 11, 36, 14, 545677)),
        ),
    ]
